spring.application.name=job-portal-backend

spring.datasource.url=jdbc:mysql://localhost:3306/job_portal
spring.datasource.username=root
spring.datasource.password=Root@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

jwt.secret=ThisIsASecretKeyForJobPortalApplicationMakeItLongAndSecure123456
jwt.expiration=86400000